name: release

on:
  push:
#    tags:
#      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

#      - id: get_version
#        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19' # The Go version to download (if necessary) and use.

      - name: Build
        run: make build

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.NEON_DOCKERHUB_USERNAME }}
          password: ${{ secrets.NEON_DOCKERHUB_PASSWORD }}

      - name: Build and push controlelr image
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: neondatabase/neonvm-controller:latest
